# docker-compose.yml
version: '3.8'

services:
  # Serviço Nginx (servidor web)
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # Serviço PHP - AGORA COM 'BUILD'
  php:
    build: # Usaremos um Dockerfile local para construir a imagem do PHP
      context: .
      dockerfile: docker/php/Dockerfile # Caminho para o Dockerfile que criaremos
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - mysql
    # Não precisa de 'command' ou 'entrypoint' explícitos aqui, o Dockerfile vai cuidar disso

  # Serviço MySQL (banco de dados)
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: